name: Build and Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Build and Release'
        required: true
      note:
        description: 'Release note'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build
        run: |
          npm i -g @vercel/ncc
          npm i @actions/github
          npm run build
      - name: Commit
        run: |
          git config --global user.name '00zhiyu'
          git config --global user.email '170500481+00zhiyu@users.noreply.github.com'
          git commit -am "dist build"
          git push

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Pull latest
        run: |
          git config --global user.name '00zhiyu'
          git config --global user.email '170500481+00zhiyu@users.noreply.github.com'
          git pull
      - name: Tag it
        run: |
          git tag -a ${{ github.event.inputs.tag }} -m "${{ github.event.inputs.note }}" 
          git push --tags
      - name: Release
        uses: actions/create-release@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: Release ${{ github.event.inputs.tag }}
          body: ${{ github.event.inputs.note }}
          draft: false
          prerelease: false
